--- #YAML:1.0
name:                CORBA-IDL
version:             2.63
abstract:            CORBA-IDL 3.0 parser
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
    Digest::SHA1:                  0
    Math::BigInt:                  1.66
    Parse::Yapp:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Francois PERRAD (francois.perrad@gadz.org)
